# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f888166f8ea76477a386f44d17981ae7"
application_url = "https://way-significance-promote-uri.trycloudflare.com"
embedded = true
name = "Rabbi Multi store redirect"
handle = "rabbi-multi-store-redirect"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://way-significance-promote-uri.trycloudflare.com/auth/callback",
  "https://way-significance-promote-uri.trycloudflare.com/auth/shopify/callback",
  "https://way-significance-promote-uri.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
